# Import dependencies
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.base import RegressorMixin
import sklearn.metrics as metrics
import pandas as pd
import numpy as np

# Generating regression dataset from sklearn.datasets
def collect_data(n_samples: int, n_features: int, n_targets: int, noise: float, random_state: int = 42) -> pd.DataFrame:
    # Use the following values: n_samples = 1000, n_features = 3, n_targets = 1,
    # noise = 0.01, random_state = 42
    ds = datasets.make_regression(n_samples=n_samples,
                            n_features=n_features,
                            n_targets=n_targets,
                            noise=noise,
                            random_state=random_state)
    # Creating Pandas dataframes from dataset generated by sklearn.datasets
    global X, y
    X = pd.DataFrame(ds[0], columns=["feature1", "feature2", "feature3"])
    y = pd.DataFrame(ds[1], columns=["target"])
    return X, y

# Splitting X and y into train and test datasets
def split_train_test(X: pd.DataFrame, y: pd.DataFrame, test_size: float, random_state: int = 42) -> pd.DataFrame:
    # Use the following values: X = X, y = y, test_size = 0.33, random_state = 42
    global X_train, X_test, y_train, y_test
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)
    return X_train, X_test, y_train, y_test

# Creating the Multiple Linear Regression model
def build_model(model: RegressorMixin, X_train: pd.DataFrame, y_train: pd.DataFrame) -> RegressorMixin:
    # Use the following values: model = LinearRegression(), X_train = X_train, y_train = y_train
    global reg
    reg = model
    reg.fit(X_train, y_train)
    return reg

# Creating prediction on test dataset
def predict_data(model: RegressorMixin, data: pd.DataFrame) -> np.ndarray:
    # Use the following values: model = reg, data = X_test
    global pred
    pred = model.predict(data)
    return pred

# Metrics to evaluate regression model
def evaluate_result(y_true: pd.DataFrame, y_pred: np.ndarray, metric: str) -> float:
    # Use the following values: y_true = y_test, y_pred = pred, metric = "MSE"
    global eval, MSE, RMSE
    eval = metric
    if eval == "MSE":
        MSE = metrics.mean_squared_error(y_true, y_pred)
        return MSE
    elif eval == "RMSE":
        MSE = metrics.mean_squared_error(y_true, y_pred)
        RMSE = np.sqrt(MSE)
        return RMSE
    else:
        return "The following metric is not available"